name: docker-build-push
description: Buildx com cache remoto em registry + push (Docker Hub)
inputs:
  image:          
    description: "Docker image name"
    required: true
  version:        
    description: "Version tag for the Docker image"
    required: true
  dockerfile:     
    description: "Path to the Dockerfile"
    required: true
    default: ./Dockerfile.native
  context:        
    description: "Docker build context path"
    required: true
    default: .
  dockerhub_user: 
    description: "Docker Hub username"
    required: true
  dockerhub_token:
    description: "Docker Hub access token"
    required: true
runs:
  using: composite
  steps:
    - uses: docker/setup-qemu-action@v3
    - uses: docker/setup-buildx-action@v3
    - uses: docker/login-action@v3
      with:
        username: ${{ inputs.dockerhub_user }}
        password: ${{ inputs.dockerhub_token }}
    - uses: docker/build-push-action@v6
      with:
        context: ${{ inputs.context }}
        file: ${{ inputs.dockerfile }}
        push: true
        tags: |
          ${{ inputs.image }}:${{ inputs.version }}
          ${{ inputs.image }}:latest
        build-args: |
          APP_VERSION=${{ inputs.version }}
        cache-from: type=registry,ref=${{ inputs.image }}:buildcache
        cache-to:   type=registry,ref=${{ inputs.image }}:buildcache,mode=max
