name: build-native
description: Build Quarkus Native (container-build) e publica runner como artifact
inputs:
  artifact_name:
    description: "Name of the artifact to be uploaded"
    required: true
    default: native-runner
runs:
  using: composite
  steps:
    - shell: bash
      run: mvn -B -ntp package -Pnative -Dquarkus.native.container-build=true
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact_name }}
        path: target/*-runner
        if-no-files-found: error
